services:
  sneakerbot:
    build: .
    container_name: sneakerbot
    restart: on-failure
    stop_grace_period: 30s
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./config/config.json:/app/config/config.json
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

