/**
 * Notification Agent: Flip Opportunity Alerts.
 */
class NotificationAgent {
    constructor(config, client) {
        this.config = config;
        this.client = client;
    }

    async send(signal) {
        if (!this.client || !this.client.isReady()) return;
        const channelId = process.env.DISCORD_CHANNEL_ID;
        if (!channelId) return;

        try {
            const channel = await this.client.channels.fetch(channelId);
            if (!channel) return;

            // Generate 3-line reason based on signal
            const reasons = [
                `1. Underpriced Opportunity: Asset listed at $${signal.price} with high ROI potential.`,
                signal.revenue > 0 ? `2. Verified Revenue: Listing mentions active income/sales proof.` : `2. High-Demand Niche: Platform data suggests strong liquidity for '${signal.source}'.`,
                signal.description.length < 150 ? `3. Unpolished Gem: Short description suggests a motivated seller or fix-and-flip opportunity.` : `3. Scaling Potential: Professional asset ready for immediate monetization.`
            ];

            // Generate 3 next actions
            const actions = [
                `1. Inspect Asset: Click the link and verify the demo/preview.`,
                `2. Due Diligence: Message seller to confirm ${signal.source === 'Flippa' ? 'analytics/revenue' : 'transferability'}.`,
                `3. High-Confidence Move: ${signal.score > 80 ? 'Prepare immediate bid/buy-it-now.' : 'Add to watchlist and monitor for price drops.'}`
            ];

            const msg = `
🔥 **DIGITAL ARBITRAGE OPPORTUNITY**

**Score:** ${signal.score}% Confidence Level

**Why this is worth consideration:**
${reasons.join('\n')}

**Suggested Next Actions:**
${actions.join('\n')}

**Financials:**
- **Price:** $${signal.price.toFixed(2)}
- **Revenue:** ${signal.revenue > 0 ? '$' + signal.revenue.toFixed(2) + ' (reported)' : 'Unknown / Micro-SaaS'}

**Platform & URL:**
- **Source:** ${signal.source}
- **Link:** ${signal.link}

---
*Alert generated by Digital Arbitrage Scout Agent (Billionaire Partner Mode)*
`;
            await channel.send(msg);
            console.log(`[MONEY] ALERT SENT: ${signal.title} (${signal.score}%)`);
        } catch (error) {
            console.error(`[NOTIFICATION ERROR] ${error.message}`);
        }
    }
}

module.exports = NotificationAgent;
